services:
  shopping.api:
    image: lanchinho/shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shopping.client:
    image: lanchinho/shoppingclient
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.db:
    image: mongo
